syntax = "proto3";
package pb;

// <DO NOT MODIFY THIS LINE> __GRPC_HELPER_SEGMENT_PB_MESSAGE_BEGIN__

// <DO NOT MODIFY THIS LINE> __GRPC_HELPER_SEGMENT_PB_MESSAGE_END__

service {{.ProjName}} {
// <DO NOT MODIFY THIS LINE> __GRPC_HELPER_SEGMENT_PB_SERVICE_BEGIN__

// <DO NOT MODIFY THIS LINE> __GRPC_HELPER_SEGMENT_PB_SERVICE_END__
}
